
name: Antons Workflow

on: [push]

jobs:
  hello-nedap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build with maven
        run: mvn --bach-mode --update-snapshots verify

        #Checkout if the pushed file has a pom.xml
      - name: Check checkout
        run: cat pom.xml

      - name: Hello Nedap
        run: echo "Hello Nedap"

      - name: Something else
        run: echo

